### ISSUE TITLE
Doesn't build on linux

### ISSUE THREAD

**Issue by abraxa** [memecode/i.Hex#1]
Hello,

I would like to try out your project on linux but the supplied Makefile.linux neither provides common make targets, not does it even work because it contains hard-coded paths (e.g. "/home/matthew/Code/Lgi/trunk/$(BuildDir)").

I appreciate that you attempt to provide linux support but unfortunately, it doesn't quite seem there yet. Better support would be nice :)

**Comment by memecode** [comment]
I've pushed a fix for that path issue. And also updated the LGI IDE to not generate absolute paths for dependencies anymore (the makefile is generated by LgiIde).

**Comment by memecode** [comment]
Fyi I'm migrating all my code to BitBucket and mercurial. So if you want to keep up to date you'll need to go to bitbucket.org/memecode and grab the source from there. i.Hex hasn't been migrated YET but I plan to do it later today.
